# Default values for myapp.

# Docker image details
image:
  repository: localhost:5000/myapp
  tag: 1.33
  imagePullPolicy: Never

# Replicas of your application in the Kubernetes cluster
replicaCount: 1

# Kubernetes service settings
service:
  name: myapp-service
  type: ClusterIP
  port: 80
  targetPort: 8080

# Environment settings (to be injected into containers)
environment: production

# Helm values for application deployment
deployment:
  name: myapp-deployment
  namespace: default
